---
# set fact os vars for CentOS:

- name: get os_version from /etc/os-release
  when: ansible_os_family is not defined
  raw: "grep '^VERSION_ID=' /etc/os-release | sed s'/VERSION_ID=//'"
  register: os_version
  changed_when: False

- name: get distro name from /etc/os-release
  when: ansible_os_family is not defined
  raw: "grep '^NAME=' /etc/os-release | sed s'/NAME=//'"
  register: distro
  changed_when: False

- name: set fact ansible_os_family var to RedHat
  when:
    - ansible_os_family is not defined
    - "'CentOS' in distro.stdout"
  set_fact:
    ansible_os_family: RedHat
