---
- name: check if firewalld is running
  shell: systemctl status firewalld
  register: firewalld
  failed_when: ( firewalld.rc not in [ 0, 3, 4 ] )

- name: firewalld ports for Linstor Controller/Satellite connections
  firewalld:
    port: 3376/tcp
    permanent: true
    immediate: true
    state: enabled
  when: firewalld.rc == 0

- name: firewalld ports for Linstor Controller REST client connections
  firewalld:
    port: 3370/tcp
    permanent: true
    immediate: true
    state: enabled
  when: firewalld.rc == 0

- name: Enable and start Linstor Controller
  systemd:
    name: linstor-controller.service
    daemon_reload: yes
    state: restarted
    enabled: yes

- name: sleep for 30 seconds and continue with play
  wait_for: timeout=30

- name: Initialize the Linstor control node as pure Controller
  shell: linstor node create {{ ansible_nodename }} {{ ansible_all_ipv4_addresses | ipaddr(drbd_replication_network) | first }} --node-type Controller
  when: "'satellite' not in group_names"
  register: linstor_create_result
  failed_when: ( linstor_create_result.rc not in [ 0, 10 ] )

- name: Initialize the Linstor control node as a Combined type
  shell: linstor node create {{ ansible_nodename }} {{ ansible_all_ipv4_addresses | ipaddr(drbd_replication_network) | first }} --node-type Combined
  when: "'satellite' in group_names"
  register: linstor_create_result
  failed_when: ( linstor_create_result.rc not in [ 0, 10 ] )
