---
dependencies:
  - { role: commons/os-checker }
  - { role: commons/pre-install, lb_rpm_pkgs: ["kmod-drbd", "drbd", "linstor-controller", "linstor-satellite", "linstor-client", "python-linstor"] }
