---
- name: gather facts from controller (needed when playbook --limit excludes controller)
  setup:
  delegate_to: "{{item}}"
  delegate_facts: True
  loop: "{{groups['controller']}}"

- name: setup linstor-client.conf
  template: src=linstor-client.j2 dest=/etc/linstor/linstor-client.conf

- name: check if firewalld is running (RHEL)
  shell: systemctl status firewalld
  register: firewalld
  failed_when: ( firewalld.rc not in [ 0, 3, 4 ] )
  when: ansible_os_family == 'RedHat'

- name: firewalld ports for LINSTOR Satellite
  firewalld:
    port: 3366/tcp
    permanent: true
    immediate: true
    state: enabled
  when: firewalld.rc is defined and firewalld.rc == 0

- name: firewalld ports for DRBD
  firewalld:
    port: 7000-8000/tcp
    permanent: true
    immediate: true
    state: enabled
  when: firewalld.rc is defined and firewalld.rc == 0

- name: check if UFW is running (Ubuntu)
  shell: ufw status
  changed_when: false
  register: ufw
  when: ansible_os_family == 'Debian'

- name: ufw ports for DRBD
  ufw:
    rule: allow
    proto: tcp
    port: 7000:8000
  when: ufw.rc is defined and 'inactive' not in ufw.stdout

- name: ufw ports for LINSTOR Satellite
  ufw:
    rule: allow
    proto: tcp
    port: "3366"
  when: ufw.rc is defined and 'inactive' not in ufw.stdout

- name: enable and start LINSTOR Satellite
  systemd:
    name: linstor-satellite.service
    daemon_reload: yes
    state: restarted
    enabled: yes

- name: sleep for 30 seconds and continue with play
  wait_for: timeout=30

- name: join LINSTOR cluster as satellite node
  shell: linstor node create {{ ansible_nodename }} {{ ansible_all_ipv4_addresses | ipaddr(drbd_replication_network) | first }} --node-type Satellite
  register: linstor_create_result
  failed_when: ( linstor_create_result.rc not in [ 0, 10 ] )

- name: create thin file backed storage pool directory
  file:
    path: /var/lib/linstor/file-thin-storage-pool
    state: directory
    mode: '0755'

- name: create the storage pool for file-thin
  shell: linstor storage-pool create filethin {{ ansible_nodename }} file-thin /var/lib/linstor/file-thin-storage-pool
  register: storage_pool_create_result
  failed_when: ( storage_pool_create_result.rc not in [ 0, 10 ] )
