---
- name: gather facts from controller (needed when playbook --limit excludes controller)
  setup:
  delegate_to: "{{item}}"
  delegate_facts: True
  loop: "{{groups['controller']}}"

- name: Setup linstor-client.conf
  template: src=linstor-client.j2 dest=/etc/linstor/linstor-client.conf

- name: check if firewalld is running
  shell: systemctl status firewalld
  register: firewalld
  failed_when: ( firewalld.rc not in [ 0, 3, 4 ] )

- name: firewalld ports for Linstor Satellite
  firewalld:
    port: 3366/tcp
    permanent: true
    immediate: true
    state: enabled
  when: firewalld.rc == 0

- name: firewalld ports for DRBD
  firewalld:
    port: 7000-8000/tcp
    permanent: true
    immediate: true
    state: enabled
  when: firewalld.rc == 0

- name: Enable and start Linstor Satellite
  systemd:
    name: linstor-satellite.service
    daemon_reload: yes
    state: restarted
    enabled: yes

- name: sleep for 30 seconds and continue with play
  wait_for: timeout=30

- name: Join Linstor cluster as satellite node
  shell: linstor node create {{ ansible_nodename }} {{ ansible_all_ipv4_addresses | ipaddr(drbd_replication_network) | first }} --node-type Satellite
  register: linstor_create_result
  failed_when: ( linstor_create_result.rc not in [ 0, 10 ] )
