- name: Create the storage pool definition for thin-lvm
  shell: linstor storage-pool-definition create thin-lvm
  run_once: true
  register: storage_pool_def_create_result
  failed_when: ( storage_pool_def_create_result.rc not in [ 0, 10 ] )

- name: Create the storage pool for thin-lvm
  shell: linstor storage-pool create lvmthin {{ ansible_nodename }} thin-lvm drbdpool/thinpool
  register: storage_pool_create_result
  failed_when: ( storage_pool_create_result.rc not in [ 0, 10 ] )
