---
dependencies:
  - { role: commons/os-checker }
  - { role: commons/pre-install, lb_rpm_pkgs: ["kmod-drbd", "drbd", "drbdtop", "linstor-controller", "linstor-client", "linstor-satellite", "python-linstor", "screen"] }
